import Head from 'next/head'

import Header from "../components/Header";

import ContactButton from "../components/ContactButton";
import MenuManager from "../components/Menu/MenuManager";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <div className="main-container" id="main-container">
        <h1>
          Bleu <br /> Blanc <br /> Studio
        </h1>
        <ContactButton />
      </div>


    </div>
  )
}
